services:

  philter:
    image: philterd/philter-api-ref
    ports:
      - "8081:8080"

  philter-ai-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - philter
    volumes:
      - ./config.test.yaml:/app/config.yaml:ro
    environment:
      - PHILTER_PROXY_CONFIG=/app/config.yaml
